# Generated by Django 4.1.7 on 2023-05-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_alter_wikientry_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikientry',
            name='images',
            field=models.URLField(default='https://i.imgur.com/LgDJFVK.jpg'),
            preserve_default=False,
        ),
    ]
