# Generated by Django 4.1.7 on 2023-05-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0003_wikientry_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikientry',
            name='edits',
            field=models.IntegerField(default=0),
        ),
    ]
